version: '3.8'

services:
  app:
    build: .
    container_name: go_phonebook
    ports:
      - "8099:8099"
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_PASS: rootpass 
      DB_HOST: db
      DB_PORT: 3309
      DB_NAME: contactsdb
    networks:
      - appnet

  db:
    image: mysql:8
    container_name: mysql_db
    restart: on-failure:3
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: contactsdb
    ports:
      - "3309:3309"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - appnet

volumes:
  mysql_data:

networks:
  appnet:
